/**
 * Sanitizes raw HTML from LLM responses for safe and beautiful use in TipTap editor.
 *
 * - Strips literal '\n', '\r' escaped string sequences generated by LLM JSON output
 * - Strips any stray bracketed coaching notes like `[Question: ...]` or `[Insert ...]`
 * - Evaluates literal JS date expressions like `" + new Date()... + "`
 * - Strips <script>, <meta>, <link>, <style> tags
 * - Normalizes pseudo-bullet paragraphs (`<p>• ...</p>`) into semantic `<ul><li>` lists
 * - Strips class, id, and disruptive style attributes from container tags so dark themes don't pollute the canvas
 * - Removes on* event handlers and javascript: hrefs
 * - Unwraps top-level container shell → returns body innerHTML only
 */
export function sanitizeResumeHtml(html) {
    if (!html || typeof html !== 'string') return ''

    let cleaned = html
        // Replace unescaped literal '\n' string sequences (backslash + n) with clean space
        .replace(/\\n/g, ' ')
        .replace(/\\r/g, '')
        // Strip stray bracketed coaching placeholders (e.g. [Question: How did you...], [Insert Metric])
        .replace(/\[\s*(?:Question|Note|Tip|Critique|Action|Clarify|Metric|Insert|TODO)[^\]]*\]/gi, '')
        // Fix LLM JS date string interpolations like " + new Date().toLocaleDateString(...) + "
        .replace(/"\s*\+\s*new Date\(\)[^"]*"\s*\+\s*"/gi, new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }))
        .replace(/["']\s*\+\s*new Date\(\)[^"']*["']/gi, new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }))

    const parser = new DOMParser()
    const doc = parser.parseFromString(cleaned, 'text/html')

    // Remove script, meta, link, style, object, embed, iframe tags
    const removeTags = ['script', 'meta', 'link', 'style', 'object', 'embed', 'applet', 'base', 'iframe']
    removeTags.forEach(tag => {
        doc.querySelectorAll(tag).forEach(el => el.remove())
    })

    // Sanitize all elements
    doc.querySelectorAll('*').forEach(el => {
        // Strip class and id to prevent external dark theme CSS leakage
        el.removeAttribute('class')
        el.removeAttribute('id')

        const attrs = [...el.attributes]
        attrs.forEach(attr => {
            const name = attr.name.toLowerCase()
            const value = attr.value.trim().toLowerCase()

            // Remove event handlers
            if (name.startsWith('on')) {
                el.removeAttribute(attr.name)
                return
            }

            // Remove javascript: hrefs / srcs
            if ((name === 'href' || name === 'src' || name === 'action') &&
                (value.startsWith('javascript:') || value.startsWith('vbscript:'))) {
                el.removeAttribute(attr.name)
                return
            }

            // Sanitize and clean href attributes from escaped quotes or backslashes (e.g. \"https://...\" or "https://...\")
            if (name === 'href') {
                let cleanHref = attr.value
                    .replace(/^[\s\\"']+|[\s\\"']+$/g, '')
                    .replace(/\\"/g, '')
                    .replace(/\\'/g, '')
                    .replace(/\\\\/g, '')
                    .trim()

                if (cleanHref) {
                    el.setAttribute('href', cleanHref)
                } else {
                    el.removeAttribute('href')
                }
                return
            }

            // Clean style attribute: strip disruptive backgrounds, absolute positioning, and overflows
            if (name === 'style') {
                let styleVal = attr.value
                styleVal = styleVal
                    .replace(/(min-width|max-width|min-height|max-height|position\s*:\s*(?:absolute|fixed)|clear|background|background-color|color\s*:\s*(?:#fff|white)|overflow|overflow-x|overflow-y|margin-top|margin-bottom|padding-top|padding-bottom)\s*:[^;]+(;|$)/gi, '')
                    .trim()

                if (!styleVal) {
                    el.removeAttribute('style')
                } else {
                    el.setAttribute('style', styleVal)
                }
            }
        })
    })

    // Convert consecutive pseudo-bullet <p> tags into semantic <ul><li>
    if (doc.body) {
        const paragraphs = Array.from(doc.body.querySelectorAll('p'))
        paragraphs.forEach(p => {
            const rawText = (p.textContent || '').trim()
            if (/^[•\-\*▪⁃]\s+/.test(rawText)) {
                const cleanText = p.innerHTML.replace(/^\s*[•\-\*▪⁃]\s+/, '')
                const li = doc.createElement('li')
                li.innerHTML = cleanText

                const prevEl = p.previousElementSibling
                if (prevEl && prevEl.tagName === 'UL') {
                    prevEl.appendChild(li)
                    p.remove()
                } else {
                    const ul = doc.createElement('ul')
                    ul.appendChild(li)
                    p.replaceWith(ul)
                }
            }
        })
    }

    // Unwrap top-level single wrapper divs if present (e.g. <div class="resume">...</div>)
    if (doc.body) {
        let children = Array.from(doc.body.children).filter(child => child.tagName !== 'SCRIPT' && child.tagName !== 'STYLE')
        while (children.length === 1 && children[0].tagName === 'DIV') {
            doc.body.innerHTML = children[0].innerHTML
            children = Array.from(doc.body.children).filter(child => child.tagName !== 'SCRIPT' && child.tagName !== 'STYLE')
        }
    }

    return (doc.body?.innerHTML || '').trim()
}

/**
 * Extracts plain text from an HTML string (for copy-to-clipboard).
 */
export function htmlToPlainText(html) {
    if (!html) return ''
    const cleaned = html.replace(/\\n/g, '\n').replace(/\\r/g, '')
    const doc = new DOMParser().parseFromString(cleaned, 'text/html')
    return doc.body?.textContent || ''
}

/**
 * Parses and sanitizes a replacement snippet or section update from the AI Assistant before applying to the document.
 *
 * - Strips markdown code fences (```suggestion...```, ```html...```, etc.)
 * - Strips coaching brackets ([Question: ...], [Insert Metric], etc.)
 * - Converts inline Markdown formatting (bold **text**, italic *text*, links [text](url)) into clean semantic HTML
 * - Cleans HTML tags via DOMParser (strips dangerous tags, scripts, dark theme CSS classes)
 * - Returns clean, TipTap-compatible HTML or text
 */
export function parseAndSanitizeSnippet(snippet) {
    if (!snippet || typeof snippet !== 'string') return ''

    let text = snippet
        // Strip markdown fences: ```suggestion, ```html, ```markdown, etc.
        .replace(/^```[a-zA-Z0-9_-]*\s*\n?/gm, '')
        .replace(/\n?```$/gm, '')
        .replace(/\\n/g, ' ')
        .replace(/\\r/g, '')
        // Strip coaching questions / placeholders
        .replace(/\[\s*(?:Question|Note|Tip|Critique|Action|Clarify|Metric|Insert|TODO)[^\]]*\]/gi, '')
        .trim()

    // Convert Markdown Headings: ### HEADING -> <h2>HEADING</h2> or <h3>
    text = text
        .replace(/^###\s+(.*?)$/gm, '<h3>$1</h3>')
        .replace(/^##\s+(.*?)$/gm, '<h2>$1</h2>')
        .replace(/^#\s+(.*?)$/gm, '<h1>$1</h1>')

    // Convert common inline Markdown to semantic HTML
    text = text
        // Markdown links: [text](url) -> <a href="url">text</a>
        .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>')
        // Markdown bold: **text** or __text__ -> <strong>text</strong>
        .replace(/(\*\*|__)(.*?)\1/g, '<strong>$2</strong>')
        // Markdown italic: *text* or _text_ -> <em>text</em>
        .replace(/(?<!\*)\*([^*]+)\*(?!\*)/g, '<em>$1</em>')
        .replace(/(?<!_)_([^_]+)_(?!_)/g, '<em>$1</em>')

    // Convert bullet lists: lines starting with • or - or * -> <li>...</li>
    const lines = text.split(/\r?\n/)
    let inList = false
    const formattedLines = []

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i].trim()
        if (/^[•\-\*]\s+/.test(line)) {
            if (!inList) {
                formattedLines.push('<ul>')
                inList = true
            }
            const cleanBullet = line.replace(/^[•\-\*]\s+/, '')
            formattedLines.push(`<li>${cleanBullet}</li>`)
        } else {
            if (inList) {
                formattedLines.push('</ul>')
                inList = false
            }
            if (line) {
                // If line isn't already a heading or paragraph tag, wrap in <p>
                if (/^<h[1-6]>/i.test(line) || /^<p>/i.test(line) || /^<ul>/i.test(line)) {
                    formattedLines.push(line)
                } else {
                    formattedLines.push(`<p>${line}</p>`)
                }
            }
        }
    }
    if (inList) {
        formattedLines.push('</ul>')
    }

    const processedHtml = formattedLines.join('\n')
    return sanitizeResumeHtml(processedHtml)
}

