/**
 * Sanitizes raw HTML from LLM responses for safe use in TipTap editor.
 *
 * - Strips literal '\n', '\r' escaped string sequences generated by LLM JSON output
 * - Evaluates literal JS date expressions like `" + new Date()... + "`
 * - Strips <script>, <meta>, <link>, <style> tags
 * - Strips class, id, and style attributes from container tags so LLM dark themes don't pollute the canvas
 * - Strips background-color, color, width, height, position, float inline styles
 * - Removes on* event handlers and javascript: hrefs
 * - Unwraps top-level container shell → returns body innerHTML only
 */
export function sanitizeResumeHtml(html) {
    if (!html || typeof html !== 'string') return ''

    let cleaned = html
        // Replace unescaped literal '\n' string sequences (backslash + n) with clean space
        .replace(/\\n/g, ' ')
        .replace(/\\r/g, '')
        // Fix LLM JS date string interpolations like " + new Date().toLocaleDateString(...) + "
        .replace(/"\s*\+\s*new Date\(\)[^"]*"\s*\+\s*"/gi, new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }))
        .replace(/["']\s*\+\s*new Date\(\)[^"']*["']/gi, new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }))

    const parser = new DOMParser()
    const doc = parser.parseFromString(cleaned, 'text/html')

    // Remove script, meta, link, style, object, embed, iframe tags
    const removeTags = ['script', 'meta', 'link', 'style', 'object', 'embed', 'applet', 'base', 'iframe']
    removeTags.forEach(tag => {
        doc.querySelectorAll(tag).forEach(el => el.remove())
    })

    // Sanitize all elements
    doc.querySelectorAll('*').forEach(el => {
        // Strip class and id to prevent external dark theme CSS leakage
        el.removeAttribute('class')
        el.removeAttribute('id')

        const attrs = [...el.attributes]
        attrs.forEach(attr => {
            const name = attr.name.toLowerCase()
            const value = attr.value.trim().toLowerCase()

            // Remove event handlers
            if (name.startsWith('on')) {
                el.removeAttribute(attr.name)
                return
            }

            // Remove javascript: hrefs / srcs
            if ((name === 'href' || name === 'src' || name === 'action') &&
                (value.startsWith('javascript:') || value.startsWith('vbscript:'))) {
                el.removeAttribute(attr.name)
                return
            }

            // Clean style attribute: strip background, color, height, width, float, position
            if (name === 'style') {
                let styleVal = attr.value
                styleVal = styleVal
                    .replace(/(width|min-width|max-width|height|min-height|max-height|position|float|clear|background|background-color|color|font-family|overflow|overflow-x|overflow-y|margin|padding)\s*:[^;]+(;|$)/gi, '')
                    .trim()

                if (!styleVal) {
                    el.removeAttribute('style')
                } else {
                    el.setAttribute('style', styleVal)
                }
            }
        })
    })

    // Unwrap top-level single wrapper divs if present (e.g. <div class="resume">...</div>)
    if (doc.body) {
        let children = Array.from(doc.body.children).filter(child => child.tagName !== 'SCRIPT' && child.tagName !== 'STYLE')
        if (children.length === 1 && children[0].tagName === 'DIV') {
            doc.body.innerHTML = children[0].innerHTML
        }
    }

    return (doc.body?.innerHTML || '').trim()
}

/**
 * Extracts plain text from an HTML string (for copy-to-clipboard).
 */
export function htmlToPlainText(html) {
    if (!html) return ''
    const cleaned = html.replace(/\\n/g, '\n').replace(/\\r/g, '')
    const doc = new DOMParser().parseFromString(cleaned, 'text/html')
    return doc.body?.textContent || ''
}
